mods:
    - name: "AutoDeconstruct"
    - name: "Squeak Through"
    - name: "Todo-List"
    - name: "Bottleneck"
    - name: "Warehousing"
    - name: "Robocharger"
    - name: "kry-inserters"
    - name: "helmod" # https://mods.factorio.com/mod/helmod
    - name: "Side Inserters" # https://mods.factorio.com/mod/Side%20Inserters
    - name: "YARM" # https://mods.factorio.com/mod/YARM
    - name: "graftorio" # https://mods.factorio.com/mod/graftorio
    - name: "Power Armor MK3" # https://mods.factorio.com/mod/Power%20Armor%20MK3
    - name: "research-progress" # https://mods.factorio.com/mod/research-progress
    - name: "LogisticTrainNetwork" # https://mods.factorio.com/mods/Optera/LogisticTrainNetwork
    - name: "LTN_Combinator_Fix" # https://mods.factorio.com/mod/LTN_Combinator_Fix
    - name: "flib" # https://mods.factorio.com/mod/flib
